# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 576)
        MainWindow.setFixedSize(860, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 310, 861, 271))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("")
        self.textEdit_2.setObjectName("textEdit_2")
        self.conclusion = QtWidgets.QTextBrowser(self.centralwidget)
        self.conclusion.setGeometry(QtCore.QRect(0, 270, 861, 41))
        self.conclusion.setStyleSheet("background-color: rgb(125, 200, 200);\n" "")
        self.conclusion.setObjectName("textBrowser")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, 230, 431, 41))
        self.frame.setStyleSheet(
            "background-color: rgb(85, 255, 0);\n"
            "background-color: rgb(148, 206, 120);"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.rewriteButton = QtWidgets.QPushButton(self.frame)
        self.rewriteButton.setGeometry(QtCore.QRect(0, 0, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.rewriteButton.setFont(font)
        # self.rewriteButton.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.rewriteButton.setObjectName("pushButton")
        self.rewriteButton.setStyleSheet("QPushButton {\n"
                                         "    border-radius: 7px;\n"
                                         "    background-color:#6240C2;\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "    background-color: rgb(148, 206, 120);\n"
                                         "    height: 35px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #81b369;\n"
                                         "}")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 230, 431, 41))
        self.frame_2.setStyleSheet(
            "background-color: rgb(85, 255, 0);\n"
            "background-color: rgb(148, 206, 120);"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.AskGPTButton = QtWidgets.QPushButton(self.frame_2)
        self.AskGPTButton.setStyleSheet("QPushButton {\n"
                                         "    border-radius: 7px;\n"
                                         "    background-color:#6240C2;\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "    background-color: rgb(148, 206, 120);\n"
                                         "    height: 35px;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #81b369;\n"
                                         "}")
        self.AskGPTButton.setGeometry(QtCore.QRect(0, 0, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.AskGPTButton.setFont(font)
        # self.AskGPTButton.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.AskGPTButton.setObjectName("pushButton_2")
        self.reqText = QtWidgets.QTextEdit(self.centralwidget)
        self.reqText.setGeometry(QtCore.QRect(0, 40, 861, 192))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reqText.setFont(font)
        self.reqText.setStyleSheet("")
        self.reqText.setObjectName("textEdit_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 861, 41))
        self.textBrowser_2.setStyleSheet("background-color: rgb(125, 200, 200);\n" "")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(820, 0, 41, 41))
        # self.label.setStyleSheet("background-image: url(:/ChatGPT_logo.svg.png);")
        self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap(r':\App\resources\ui\ChatGPT_logo.svg.png'))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.conclusion.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt; font-weight:600; color:#ffffff;">Исправленный текст:</span></p></body></html>',
            )
        )
        self.rewriteButton.setText(_translate("MainWindow", "Исправить"))
        self.AskGPTButton.setText(_translate("MainWindow", "Спросить у GPT"))
        self.textBrowser_2.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt; font-weight:600; color:#ffffff;">Текст:</span></p></body></html>',
            )
        )
